"""
Controlled Clinical Vocabulary
================================
Source-of-truth for abbreviation expansion, synonym resolution, and regex
pattern generation used by EVERY component in the pipeline:
  • clinical_dict.py    — fast dictionary NER pre-pass
  • query_normalizer    — CI text expansion before retrieval
  • aggregator          — contradiction scoring
  • reranker            — entity overlap, intent alignment, sub-intent classification

Endpoint term knowledge (ORR synonyms, PFS synonyms, …) is loaded at module
init from shared/data/endpoint_concepts.json — generated by
tools/build_endpoint_ontology.py using NCI Thesaurus concept IDs.  This makes
every component consistent: if the JSON says "durable response rate" is an ORR
synonym, it is treated that way everywhere, not just in the reranker.

Non-endpoint entries (drugs, diseases, regulatory, abbreviations) remain
curated here — NCIt does not model them reliably.

IMPORTANT: Do NOT let an LLM populate this table.  Domain experts must curate
every entry.  An LLM may *suggest* additions, but only a verified clinical
vocabulary (or your internal dictionary) is the authoritative source.

In regulated environments precision matters — a wrong synonym causes false
positives that waste reviewer time and erode trust.
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Endpoint synonym table — loaded from shared/data/endpoint_concepts.json
# ─────────────────────────────────────────────────────────────────────────────
# {category_label: frozenset[synonym_str]}  e.g. {"orr": frozenset({...}), ...}
#
# ENDPOINT_SYNONYMS is the single source of truth for endpoint term matching
# across the entire pipeline.  Components query it via get_endpoint_synonyms().
#
# Populated at module init; falls back to {} (sub-intent matching disabled)
# when the JSON is absent so no component crashes.

def _load_clinical_concepts_json() -> tuple[dict[str, frozenset[str]], dict[str, dict]]:
    """
    Locate and load shared/data/clinical_concepts.json.

    Resolution order (stops at first hit):
      1. shared/data/clinical_concepts.json   — canonical, written by build tool
      2. reranker/data/clinical_concepts.json — mirror for Lambda packages
      3. shared/data/endpoint_concepts.json   — legacy name (backward compat)
      4. reranker/data/endpoint_concepts.json — legacy mirror

    OS guard: the bare "os" token is space-padded to " os " to prevent
    substring collision with "those", "dose", "close", etc.

    Returns:
      (categories, metadata)
      categories : {category_name: frozenset[synonym_str]}
      metadata   : {category_name: {"group": str, "canonical_name": str}}
    Both dicts are empty on failure — no component crashes.
    """
    base = Path(__file__).parent
    reranker_base = base.parent / "lambdas" / "search" / "reranker" / "data"
    candidates = [
        base / "data" / "clinical_concepts.json",
        reranker_base / "clinical_concepts.json",
        base / "data" / "endpoint_concepts.json",    # legacy
        reranker_base / "endpoint_concepts.json",    # legacy
    ]
    for path in candidates:
        if not path.exists():
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            raw: dict[str, list[str]] = data.get("categories", {})
            if not raw:
                continue
            meta: dict[str, dict] = data.get("metadata", {})
            result: dict[str, frozenset[str]] = {}
            for cat, syns in raw.items():
                kws: set[str] = set()
                for s in syns:
                    kws.add(" os " if (cat == "os" and s.strip() == "os") else s)
                result[cat] = frozenset(kws)
            total = sum(len(v) for v in result.values())
            logger.info(
                "[clinical_ontology] %s loaded: %d synonyms across %d categories (built %s)",
                path.name, total, len(result), data.get("built_at", "?"),
            )
            return result, meta
        except Exception as exc:
            logger.warning("[clinical_ontology] %s unreadable: %s", path, exc)

    logger.warning(
        "[clinical_ontology] clinical_concepts.json not found — "
        "synonym matching falls back to hardcoded ABBREVIATIONS entries.  "
        "Run tools/build_endpoint_ontology.py to generate it."
    )
    return {}, {}


# All NCIt-backed synonyms, indexed by category name.
# Covers: endpoints, response criteria, diseases, drugs, targets, AE types,
#         lab tests, statistical methods, clinical trial roles.
ENDPOINT_SYNONYMS: dict[str, frozenset[str]]
_CONCEPT_METADATA: dict[str, dict]
ENDPOINT_SYNONYMS, _CONCEPT_METADATA = _load_clinical_concepts_json()

# ─────────────────────────────────────────────────────────────────────────────
# Helpers to pull NCIt synonyms into structured vocabulary dicts
# ─────────────────────────────────────────────────────────────────────────────

def _ncit_synonyms(category: str, fallback: list[str]) -> list[str]:
    """
    Return NCIt-backed synonyms for *category* as a sorted list.

    Short all-uppercase tokens (≤5 chars) are excluded from the returned list
    because they belong as keys in ABBREVIATIONS, not as expansion values.
    Falls back to *fallback* when the JSON is absent or the category is empty.
    """
    syns = ENDPOINT_SYNONYMS.get(category, frozenset())
    cleaned = sorted(s for s in syns if not (len(s) <= 5 and s == s.upper()))
    return cleaned if cleaned else fallback

# Keep _endpoint_expansions as an alias for backward compatibility
_endpoint_expansions = _ncit_synonyms


def _auto_populate(prefix: str) -> dict[str, list[str]]:
    """
    Build a vocabulary dict from every category whose name starts with *prefix*.

    Key  = category’s canonical_name from build-tool metadata (e.g. "daratumumab"),
           or the bare suffix after *prefix* when canonical_name is absent.
    Value = all synonyms for that category, sorted.

    This means adding a new drug/disease/role to tools/build_endpoint_ontology.py
    and re-running the build is the ONLY step needed — zero changes here.
    """
    out: dict[str, list[str]] = {}
    for cat, syns in ENDPOINT_SYNONYMS.items():
        if cat.startswith(prefix):
            canonical = (
                _CONCEPT_METADATA.get(cat, {}).get("canonical_name")
                or cat[len(prefix):]
            )
            out[canonical] = sorted(syns)
    return out

# ─────────────────────────────────────────────────────────────────────────────
# Abbreviation → canonical full form(s)
# Keys are stored UPPERCASE for case-insensitive lookup via .upper().
#
# Clinical-entity abbreviations (ORR, PFS, OS, …) pull their expansions from
# ENDPOINT_SYNONYMS at definition time so they stay in sync with the JSON.
# Fallback lists are provided in case the JSON is absent.
# ─────────────────────────────────────────────────────────────────────────────
ABBREVIATIONS: dict[str, list[str]] = {

    # ── Response criteria (IMWG) ─────────────────────────────────────────────
    # ORR, PFS, OS, DOR, MRD etc. pull their expansions from ENDPOINT_SYNONYMS
    # (loaded from endpoint_concepts.json — NCIt-backed).  This keeps ALL
    # components (dict pre-pass, query normalizer, aggregator, reranker)
    # consistent with the same ontology-derived vocabulary.
    "ORR":     _endpoint_expansions("orr",  ["Overall Response Rate", "Objective Response Rate"]),
    "CR":      ["Complete Response"],
    "SCR":     ["Stringent Complete Response"],
    "VGPR":    ["Very Good Partial Response"],
    "PR":      ["Partial Response"],
    "MR":      ["Minimal Response"],
    "SD":      ["Stable Disease"],
    "PD":      ["Progressive Disease"],
    "MRD":     _endpoint_expansions("mrd",  ["Minimal Residual Disease", "Measurable Residual Disease"]),
    "BOR":     _endpoint_expansions("orr",  ["Best Overall Response"]),
    "CBR":     ["Clinical Benefit Rate"],

    # ── Survival / time-to-event endpoints ───────────────────────────────────
    "PFS":     _endpoint_expansions("pfs",  ["Progression-Free Survival"]),
    "OS":      _endpoint_expansions("os",   ["Overall Survival"]),
    "DOR":     _endpoint_expansions("dor",  ["Duration of Response"]),
    "TTR":     _endpoint_expansions("ttf",  ["Time to Response"]),
    "TTNT":    ["Time to Next Treatment"],
    "TTP":     ["Time to Progression"],
    "EFS":     _endpoint_expansions("pfs",  ["Event-Free Survival"]),
    "RFS":     _endpoint_expansions("pfs",  ["Relapse-Free Survival"]),

    # ── Diseases ──────────────────────────────────────────────────────────────
    "MM":      ["Multiple Myeloma"],
    "RRMM":    ["Relapsed/Refractory Multiple Myeloma", "Relapsed Refractory Multiple Myeloma"],
    "NDMM":    ["Newly Diagnosed Multiple Myeloma"],
    "SMM":     ["Smoldering Multiple Myeloma"],
    "MGUS":    ["Monoclonal Gammopathy of Undetermined Significance"],
    "PCL":     ["Plasma Cell Leukemia"],
    "NHL":     ["Non-Hodgkin Lymphoma"],
    "DLBCL":   ["Diffuse Large B-cell Lymphoma"],
    "CLL":     ["Chronic Lymphocytic Leukemia"],
    "AML":     ["Acute Myeloid Leukemia"],
    "ALL":     ["Acute Lymphoblastic Leukemia"],
    "RRAML":   ["Relapsed/Refractory Acute Myeloid Leukemia"],

    # ── Drug targets / biomarkers ─────────────────────────────────────────────
    "BCMA":    ["B-cell Maturation Antigen", "TNFRSF17"],
    "GPRC5D":  ["G Protein-Coupled Receptor Class C Group 5 Member D"],
    "CD38":    ["Cluster of Differentiation 38"],
    "CD19":    ["Cluster of Differentiation 19"],
    "CD20":    ["Cluster of Differentiation 20"],
    "CD3":     ["Cluster of Differentiation 3"],

    # ── Treatment classes ─────────────────────────────────────────────────────
    "BITE":    ["Bispecific T-cell Engager", "Bispecific Antibody"],
    "CAR":     ["Chimeric Antigen Receptor"],
    "CART":    ["CAR T-cell Therapy", "Chimeric Antigen Receptor T-cell"],
    "IMID":    ["Immunomodulatory Drug"],
    "DARA":    ["Daratumumab"],
    "ISA":     ["Isatuximab"],
    "LEN":     ["Lenalidomide"],
    "BORT":    ["Bortezomib"],
    "CARF":    ["Carfilzomib"],
    "DEX":     ["Dexamethasone"],
    "MEL":     ["Melphalan"],
    "THAL":    ["Thalidomide"],
    "POMA":    ["Pomalidomide"],

    # ── Dosing / schedule ─────────────────────────────────────────────────────
    "RP2D":    _endpoint_expansions("dose_finding", ["Recommended Phase 2 Dose"]),
    "RPTD":    _endpoint_expansions("dose_finding", ["Recommended Phase 2 Dose"]),
    "MTD":     _endpoint_expansions("dose_finding", ["Maximum Tolerated Dose"]),
    "DLT":     _endpoint_expansions("dose_finding", ["Dose-Limiting Toxicity", "Dose Limiting Toxicity"]),
    "IV":      ["Intravenous"],
    "SC":      ["Subcutaneous"],
    "QW":      ["Once Weekly", "Every Week"],
    "Q2W":     ["Every Two Weeks", "Every 2 Weeks"],
    "Q3W":     ["Every Three Weeks", "Every 3 Weeks"],
    "Q4W":     ["Every Four Weeks", "Every 4 Weeks"],
    "BID":     ["Twice Daily"],
    "TID":     ["Three Times Daily"],
    "QD":      ["Once Daily"],
    "PK":      _endpoint_expansions("pk",   ["Pharmacokinetics"]),
    "PD":      ["Pharmacodynamics", "Progressive Disease"],  # intentional dual meaning

    # ── Adverse events ────────────────────────────────────────────────────────
    "AE":      _endpoint_expansions("safety", ["Adverse Event"]),
    "SAE":     ["Serious Adverse Event"],
    "TEAE":    ["Treatment-Emergent Adverse Event"],
    "TRAE":    ["Treatment-Related Adverse Event"],
    "IRAE":    ["Immune-Related Adverse Event"],
    "CRS":     ["Cytokine Release Syndrome"],
    "ICANS":   ["Immune Effector Cell-Associated Neurotoxicity Syndrome"],
    "IRR":     ["Infusion-Related Reaction"],
    "CTCAE":   ["Common Terminology Criteria for Adverse Events"],

    # ── Laboratory / haematology ──────────────────────────────────────────────
    "ANC":     ["Absolute Neutrophil Count"],
    "PLT":     ["Platelet Count"],
    "HGB":     ["Haemoglobin", "Hemoglobin"],
    "WBC":     ["White Blood Cell Count"],
    "LDH":     ["Lactate Dehydrogenase"],
    "SPEP":    ["Serum Protein Electrophoresis"],
    "UPEP":    ["Urine Protein Electrophoresis"],
    "IFE":     ["Immunofixation Electrophoresis"],
    "FLC":     ["Free Light Chain"],
    "SFLC":    ["Serum Free Light Chain"],
    "CMP":     ["Comprehensive Metabolic Panel"],

    # ── Regulatory / documentation ────────────────────────────────────────────
    "ICF":     ["Informed Consent Form"],
    "IRB":     ["Institutional Review Board"],
    "IEC":     ["Independent Ethics Committee"],
    "GCP":     ["Good Clinical Practice"],
    "IND":     ["Investigational New Drug"],
    "NDA":     ["New Drug Application"],
    "BLA":     ["Biologics License Application"],
    "FDA":     ["Food and Drug Administration"],
    "EMA":     ["European Medicines Agency"],
    "SAP":     ["Statistical Analysis Plan"],
    "CSR":     ["Clinical Study Report"],
    "CRF":     ["Case Report Form"],
    "DSMB":    ["Data Safety Monitoring Board"],
    "DMC":     ["Data Monitoring Committee"],

    # ── Organisations / scoring ───────────────────────────────────────────────
    "IMWG":    ["International Myeloma Working Group"],
    "ECOG":    ["Eastern Cooperative Oncology Group"],
    "ASCT":    ["Autologous Stem Cell Transplantation", "Autologous Stem Cell Transplant"],
    "HSCT":    ["Haematopoietic Stem Cell Transplantation"],
    "NCT":     ["National Clinical Trial"],
    "RECIST":  ["Response Evaluation Criteria in Solid Tumors"],
}

# ───────────────────────────────────────────────────────────────────────────────
# Role synonyms  (canonical role → aliases used in CIs and protocols)
# Dynamically populated from every role_* category in clinical_concepts.json.
# Falls back to hardcoded values when JSON predates role category support.
# ───────────────────────────────────────────────────────────────────────────────
ROLE_SYNONYMS: dict[str, list[str]] = _auto_populate("role_") or {
    "principal investigator": ["PI", "Lead Investigator", "Site Principal Investigator",
                               "Qualified Investigator", "Study Investigator"],
    "chief investigator":     ["CI", "Principal Investigator", "Lead Investigator"],
    "sub-investigator":       ["Sub-I", "Co-Investigator", "Coinvestigator"],
    "study coordinator":      ["CRC", "Site Coordinator", "Clinical Research Coordinator",
                               "Research Coordinator"],
    "sponsor":                ["Study Sponsor", "Sponsor-Investigator"],
    "monitor":                ["CRA", "Clinical Research Associate", "Site Monitor"],
}

# ───────────────────────────────────────────────────────────────────────────────
# Drug synonyms  (generic name → all known aliases, codes, brand names)
# Dynamically populated from every drug_* category in clinical_concepts.json.
# All NCIt synonyms are included without filtering.
# Add a new drug to tools/build_endpoint_ontology.py and rebuild — done.
# ───────────────────────────────────────────────────────────────────────────────
DRUG_SYNONYMS: dict[str, list[str]] = _auto_populate("drug_")
# Combination regimen — project-specific, not an NCIt concept
DRUG_SYNONYMS["tec-tal"] = [
    "teclistamab plus talquetamab",
    "talquetamab plus teclistamab",
    "JNJ-64007957 plus JNJ-64407564",
    "teclistamab/talquetamab",
]

# ───────────────────────────────────────────────────────────────────────────────
# Disease synonyms  (canonical name → variants)
# Dynamically populated from every disease_* category in clinical_concepts.json.
# ───────────────────────────────────────────────────────────────────────────────
DISEASE_SYNONYMS: dict[str, list[str]] = _auto_populate("disease_")




# ─────────────────────────────────────────────────────────────────────────────
# Public helpers
# ─────────────────────────────────────────────────────────────────────────────

def expand_abbreviation(abbr: str) -> list[str]:
    """Return known full forms for *abbr*, or [] if unknown."""
    return ABBREVIATIONS.get(abbr.strip().upper(), [])


def get_concept_synonyms(category: str) -> frozenset[str]:
    """
    Return all known synonyms for any NCIt-backed category.

    Covers endpoints, response criteria, diseases, drugs, drug targets,
    AE types, lab tests, and statistical methods — every category defined
    in tools/build_endpoint_ontology.py.

    Returns frozenset() when the category is unknown or the JSON is absent.
    """
    return ENDPOINT_SYNONYMS.get(category, frozenset())

# Backward-compatible alias
get_endpoint_synonyms = get_concept_synonyms


def get_drug_synonyms(name: str) -> list[str]:
    """Return known aliases/codes for a drug name (case-insensitive), or []."""
    return DRUG_SYNONYMS.get(name.strip().lower(), [])


def get_disease_synonyms(name: str) -> list[str]:
    """Return known variants for a disease name (case-insensitive), or []."""
    return DISEASE_SYNONYMS.get(name.strip().lower(), [])


def get_role_synonyms(role: str) -> list[str]:
    """Return curated synonyms for *role* (case-insensitive), or []."""
    return ROLE_SYNONYMS.get(role.strip().lower(), [])


def build_regex_patterns(text: str) -> list[str]:
    """
    Build a list of regex patterns covering the CI text and its known
    abbreviation / parenthetical variants.

    Patterns are returned de-duplicated and ready for ``re.search``.
    """
    patterns: list[str] = []

    # 1. Literal match of the raw text (re-escaped)
    patterns.append(re.escape(text))

    # 2. If the text IS an abbreviation, add its expansions
    for exp in expand_abbreviation(text.strip()):
        patterns.append(re.escape(exp))

    # 3. Drug synonyms (generic name or alias appears in text)
    for syns in [get_drug_synonyms(text), get_disease_synonyms(text)]:
        for s in syns:
            patterns.append(re.escape(s))

    # 4. Abbreviations embedded inside parentheses: "Overall Response Rate (ORR)"
    for abbr in re.findall(r"\(([A-Z][A-Z0-9-]+)\)", text):
        patterns.append(r"\b" + re.escape(abbr) + r"\b")
        for exp in expand_abbreviation(abbr):
            patterns.append(re.escape(exp))

    # Deduplicate while preserving order
    seen: set[str] = set()
    unique: list[str] = []
    for p in patterns:
        if p not in seen:
            seen.add(p)
            unique.append(p)
    return unique
